name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter         

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  intl: ^0.17.0
  collection: ^1.16.0
  async: ^2.8.2
  pull_to_refresh: ^2.0.0
  weather_icons: ^3.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - data/cities.json

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 500

    - family: UnitIcons
      fonts:
        - asset: fonts/UnitIcons.ttf

